encoding: utf-8
# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]
# Permalinks
# permalink:        pretty
permalink: /:basename/

# Setup
title:            Abhijit Wds Maya
tagline:          My Wedding
url:              https://abhijitmondal.in
baseurl:          "/wedding"

author:
  name:           'Abhijit Mondal'
  url:            https://abhijitmondal.in

github:
    repo:           https://github.com/abhimp/

collections:
  lbeng:
    output: true
    permalink: /beng/:path
  leng:
    output: true
    permalink: /eng/:path

# paginate:         5
paginate_path:    "blog/page:num/"
paginate: 2
# Custom vars
version:          2.1.0



repository: abhimp/abhimp.github.io
